### ISSUE TITLE
Example code in README doesn't compile

### ISSUE THREAD

**Issue by cforemanTAG** [bamcis-io/PrestoClient#11]
`ExecuteQueryV1Response` does not contain a definition for `Response`. I see `Response` exists on `ExecuteQueryV2Response`, but it doesn't appear the corresponding request object, `ExecuteQueryV2Request`, is available in the API.

**Comment by hakenmt** [comment]
I've updated the readme, thanks.

**Comment by cforemanTAG** [comment]
No problem. Thanks for the quick response!
