### ISSUE TITLE
password input?

### ISSUE THREAD

**Issue by tooptoop4** [bamcis-io/PrestoClient#3]
can connection to presto be made with password?

**Comment by VoroninDA** [comment]
Bump. I would appreciate a connection config with password property.

**Comment by hakenmt** [comment]
Ok, I think that's doable, from the sparse documentation, I'm pretty sure password authentication just uses basic http auth. Should have something working soon.

**Comment by hakenmt** [comment]
@tooptoop4 @VoroninDA I've created a beta release with password auth. I don't have anything I can personally test this out against right now. If you wouldn't mind, can you test this [release](https://github.com/bamcis-io/PrestoClient/releases/tag/v0.198.3-beta) and let me know if that works? Thanks.

**Comment by georgevanburgh** [comment]
Not op, but I quickly tested `0.198.3-beta`, and it worked perfectly against a PrestoDB instance that requires authentication. Thanks for making this change!

Are there plans to do a production release of this change at some point?

**Comment by hakenmt** [comment]
@georgevanburgh I'm not actively keeping up with this project, and I marked the past 2 releases as beta since I didn't have a good test environment (or time to build one). However, it is based on the previous release that I think was production ready, so if there's enough consensus that the password auth works as expected, I can promote it.

**Comment by georgevanburgh** [comment]
Understood. There's no pressure from me on promoting it - but let me know if you need any additional help with testing.

**Comment by Iviglious** [comment]
Hi,
If that helps I used `0.198.3-beta` NuGet package and works nice for me (used password and SSL) see Issue #5 .
My Presto cluster is version 355.
I suppose here you are talking about unit testing using your PrestoClientTests project.
I tried opening the project, but I don't have .NET 3.1 nor VS2019 (I am still stuck with VS2017) and also I'm not sure how to run the tests.

**Comment by georgevanburgh** [comment]
@hakenmt was kind enough to promote a stable version (`0.198.5`) that contains the password change, and which works fine for us. I think maybe this issue can be closed out?
