### ISSUE TITLE
Support for HTTPS (SSL)

### ISSUE THREAD

**Issue by Iviglious** [bamcis-io/PrestoClient#5]
How about adding support for HTTPS/SSL?
Our Presto cluster is setup to encrypt the connection.
When I tried using your beta release [v0.198.3-beta](https://github.com/bamcis-io/PrestoClient/releases/tag/v0.198.3-beta) (with password) I get this error:  
```
Message: The server committed a protocol violation. Section=ResponseStatusLine
Stack:    at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context)
   at System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar)
```
I think it's because our server is setup to be accessed via HTTPS.
For example, using Trino I connect to our server like that:
```
java -jar "trino-cli-355-executable.jar" "--insecure" "--server=https://my-presto-server:8080" "--user=my-user" "--password"
```
Then I type the password manually and It's working.
So I'm using HTTPS, but with the flag `--insecure` I disable the request to not be needed to use a SSL certificate.
Here is the change showing how they implemented this option: [trino Change 1484](https://github.com/trinodb/trino/pull/1484/files/a16e048c305a31f314383060c96634fbf57a3279#diff-8a3db9ce24ff35c89c8a5e8cef1d7d32202d2a2372da7b65aa0107d27d81f864)

To develop it to work with HTTPS I suppose you need to use the OpenSSL library.
If I find some time I might give it a go.

Thanks,
Iviglious

**Comment by hakenmt** [comment]
The `--insecure` flag ignores SSL cert errors, like the domain not matching cert, the cert being expired, not being trusted, etc. This library provides two options in `PrestoClientSessionConfig` for this, first `UseSsl` to tell the client to use HTTPS, and then `IgnoreSslErrors` to ignore the aforementioned issues with SSL certs. Can you try using those options and see if that works for you?

**Comment by Iviglious** [comment]
Hi @hakenmt 
Sorry, I just noticed the SSL properties - very useful.
Ok, I tested it with Presto cluster version 355 and your beta release works nicely.
Thanks.
You may close this issue (and possibly the one about the beta release).

**Comment by hakenmt** [comment]
Great, glad that worked!
